### ISSUE TITLE
Sideload a document from command argument

### ISSUE THREAD

**Issue by rvanlaak** [OfficeDev/office-toolbox#19]
The sideload option allows our less technical QA to use development builds of our addin. To simplify using the addin on specific documents, it would be great if the file that get loaded could get configured.

What about also allowing an argument instead of [calling `generateTemplateFile` in `sideloadManifest`](https://github.com/OfficeDev/office-toolbox/blob/master/src/util.ts#L489)?

**Comment by akrantz** [comment]
If you have an existing document that contains a reference to the add-in, you can just open that document. For example, if you run the sideload command and save it as an existing document, it can be re-opened later without having to run the sideload command.

If you want to take an existing document and update it to have a solution reference, that would require more work. The implementation takes a template and does simple string replacement to update the guid and version. If would be more involved to take an arbitrary document and update it. 

Perhaps it would be more feasible to not require template documents but rather have logic which could insert the relevant xml into the document, and remove any existing xml if present, such that it would work for any document whether it has an existing solution reference or not. Then, it could take an existing file to update or create a new file. Ideally, the implementation would read the existing xml and understand the structure so that it could modify the xml and save the document. Alternatively, perhaps it would be simpler to use a regular expression to modify the doc by including the xml start/end tags depending on if that is unique enough.

**Comment by rvanlaak** [comment]
Ah, the addin gets injected in the actual xml? That makes it interesting. Would that also work when the part that injects it gets extracted out? That way the XML from the document in the command arguments could get used. Any idea where the addin code gets written?

**Comment by akrantz** [comment]
The id and version for the add-in is put into the document. Take a look at [generateTemplateFile()](https://github.com/OfficeDev/office-toolbox/blob/master/src/util.ts#L512).

**Comment by napalm00** [comment]
Is there any way to sideload the add-in without having to write in the XML? It seems Office.js add ins lack the installer feature that's easier to use for many customers, and I was hoping to exploit this library as a starting point for a sideloading "installer", however having to write to the XML of the document is a big issue.

**Comment by akrantz** [comment]
Yes, see here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

**Comment by akrantz** [comment]
Please let us know whether this is something that you still need. It's been quite a while, so I'm closing the issue for now.
